import user_image from "../../assets/img/user.jpg";
export const users = [
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 2,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 3,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 4,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 5,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 6,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 7,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 8,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 9,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 10,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 11,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 12,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 13,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 14,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 15,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 16,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 17,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 18,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 19,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 20,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 21,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 22,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 23,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 24,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 25,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 26,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 27,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 28,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 29,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 30,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 31,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 32,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 33,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 34,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 35,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 36,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
  ];