import user_image from "../../assets/img/user.jpg";
export const users = [
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
    {
      id: 1,
      name: "Taufiq Widi",
      image: user_image,
      field: "Fullstack Developer",
      skill: "C/C++, Javascript, ReactJS",
      rating: 99,
      project: 99,
    },
  ];